[package]
name = "morpheus-serial"
version = "0.1.0"
edition = "2021"
maintainer = "Aurelien VALADE <aurelien.valade@balena.io>"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serialport = "4.2.0"
getopt = "1.1.3"
